version: '3'

services:
  api:
    environment:
      - DB_HOST=postgres
      - DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: "postgres:12"
    container_name: postgres
    restart: always
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: